- js/scene/special/Scene.mjs
チームメンバーが分からない実装をChatGPTに質問をする際に、僕がどのような枠組みを設計しているのかを理解した上で回答してもらいたいため、SceneクラスのJSDocを整備しました。
ChatGPTへの質問にScene.mjsのプログラムの全文を含めるだけで、このチームのプロジェクトの枠組みに合った回答が生成されると思います。
> Docs: Sceneクラスのドキュメントを整備

- js/SceneRouter.mjs
- js/scene/special/Scene.mjs
SceneのupdateStatesメソッドの第3引数として、pressedKeysを追加しました。
pressedKeysは現在押されているキーの集合で、hasメソッドを呼び出すことで特定のキーが押されているかを判別できます。
```javascript
updateStates(deltaTime, mouse, pressedKeys) {
if (pressedKeys.has("q")) {
console.log("qが押されています。")
}
}
```
> Feature: キー操作の読み取りをサポート

- js/scene/TitleScene.mjs
TitleSceneからConfigSceneに遷移できない問題を解消しました
> Fix: ConfigSceneに遷移するボタンを修正

- css/main.css
- js/SceneRouter.mjs
- js/index.mjs
Canvasを表示する画面サイズに応じてフルスクリーン表示するようにしました。
> Feature: Canvasをフルスクリーン表示

- js/gameObject/Car.mjs
- js/gameObject/Player.mjs
- js/gameObject/obstacleSettings.mjs
- js/scene/DriveScene.mjs
- js/stage/speedModes.mjs
- js/stage/stage1.mjs
真夜中・高速道路・氷河のステージのギミックをひととおり実装しました。
自機の周辺だけ明るくなります。視野が狭すぎるので新規オブジェクト「街頭」を今後実装する予定。
speedMode.normal が通常ステージ、speedMode.fast が高速道路のステージで使用するモード。
プレイヤーの操作に慣性が加わるので難易度が上がります。氷河ステージで使用予定。
> Feature: DriveSceneでのステージ固有のギミックの追加

- js/SceneRouter.mjs
- js/gameObject/Car.mjs
- js/gameObject/Mud.mjs
- js/gameObject/Player.mjs
- js/gameObject/SpeedingBoard.mjs
- js/gameObject/ingredients.mjs
- js/gameObject/pizzas.mjs
- js/resource.mjs
- js/scene/PizzaCollectionScene.mjs
close #22 
リソースの管理を行うクラス `Resource` を追加して、すべてのリソースデータを起動時に読み込み、各Sceneは
```javascript
import { resource } from '../resource.mjs';
const image = resource.images.mud; // (例) 泥の画像
ctx.drawImage(image, x, y, w, h);
```
のようにして、事前に読み込まれた画像を利用するようにしました。
> Fix: 画像のちらつきを改善

- js/scene/ResultScene.mjs
クリアタイムが目標タイムをオーバーした場合、スコアがマイナスになるように修正
> Fix: クリア時間に関するスコア計算・表示の修正

- js/SceneRouter.mjs
- js/dataObject/UserConfig.mjs
- js/dataObject/cookieKeysSettings.mjs
js/dataObject/cookieKeysSettings.mjs の defaultValueFor 関数に、各キーに対応するデフォルトのデータを記述しました。
> Feature: Cookieロード時、データがない場合はデフォルトのデータを保存する

- js/gameObject/Ingredient.mjs
- js/gameObject/Mud.mjs
- js/gameObject/SpeedingBoard.mjs
> Feature: scaleFactorを7/18の会議で話し合った大きさに変更

- js/gameObject/Player.mjs
Player 122-123行目の引数にspeedSettingを追加
> Fix: inertia導入時の不具合を修正

- js/scene/StageSelectionScene.mjs
- js/scene/WhichSlotToSaveScene.mjs
StageSelectionSceneとWhithSlotToSaveSceneの右上に現在選択しているスロットの値を表示しました
close #47
> Feature: スロット選択画面とステージ選択画面にplayingSlotIndexの値を表示

- js/scene/WhichSlotToSaveScene.mjs
> Fix: セーブ先のスロットを選択後、playingSlotIndexを更新するよう修正

- js/stage/stage3.mjs
> Fix: stage3にstageNumberを付与

- js/scene/SlotSelectionScene.mjs
- js/scene/TitleScene.mjs
close #60 
タイトル画面で"最初から始める"を選択、かつデータがあるスロットを選択した場合に、警告を出してスロットを初期化するように変更しました。
> Feature: "最初から始める"を選択した場合にスロットを初期化する機能を実装

- js/component/Joystick.mjs
- js/scene/DriveScene.mjs
- js/stage/stages.mjs
close #63
DriveSceneをジョイスティックのUIで操作できるようにしました。
画面内をタッチすると現れます。
> Feature: ジョイスティック操作を実装

- js/dataObject/Slot.mjs
- js/scene/StageSelectionScene.mjs
close #81 
ステージ番号の小さいほうから順に解放されていくように変更しました。
> Feature: ステージの遊び順の制限を設定

- js/stage/stages.mjs
> Fix: stage2に遷移できなかったため修正

- js/gameObject/pizzas.mjs
> Refactor: 残ったままのTODOコメントを削除

- js/gameObject/ingredients.mjs
> Change: 各食材の生成確率を調整

- js/scene/DriveScene.mjs
> Fix: 道路の揺らぎを修正

- js/gameObject/Ice.mjs
> Feature: 氷の当たり判定の本実装

- js/scene/DriveScene.mjs
> Change: stage4・5の道路の色を調整

- js/gameObject/endings.mjs
> Feature:endingMessageの実装

- js/gameObject/endings.mjs
主な変更点
・イタリア人ブチ切れエンドを本場リスペクトエンド変更(本場　
　のピザをたくさん作ることで到達)
・ピザ博士エンド、イタリア修行エンドの優先順位
・ピザを何枚以上集める系のエンド(入院エンド、ピザ生地職人
　エンド、海の家エンドなど)をstageResult.pizzasにおける該当
　するピザの割合で判定するように
・エンディングのヒントを修正
> Change: エンディングの条件の見直し

- js/scene/StageSelectionScene.mjs
> Feature: アンロックされていないステージの説明文を？に

- js/scene/DriveScene.mjs
- js/stage/stage5.mjs
> Change: stage5の道路の色を変更

- js/scene/CookingScene.mjs
> Feature: 調理画面に操作の説明を追加

- js/scene/DriveScene.mjs
- 車にライトを追加しました。
- それに伴って車の消滅位置を後ろにずらしました。
- 自機や街頭のライトの大きさ・位置も調整しました。
> Change: ライトの調整

- js/scene/StageSelectionScene.mjs
> Change: エンディングを見るボタンを「配達を終える」に

- js/scene/StageSelectionScene.mjs
> Change: ステージ選択画面のSTAGEのフォントをserifに変更

- js/stage/stage1.mjs
- js/stage/stage2.mjs
- js/stage/stage3.mjs
- js/stage/stage4.mjs
- js/stage/stage5.mjs
> Change: stage毎のtargetTimeの変更

- js/scene/PizzaCollectionScene.mjs
ゲテモノピザの材料の間にorをつけて条件をわかりやすくしました
> Change: ゲテモノピザの材料の表示を変更

- js/gameObject/endings.mjs
> Change: エンディング条件に必要なスコアの値を変更

- js/scene/TitleScene.mjs
this.endingが0の時はエンディングシーンに遷移するボタンを非表示にしました
> Fix: 最初からエンディングシーンに遷移できるバグを修正
